config/routes.rb
require 'api_contraints'

Highscore::Application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, contraints: ApiContraints.new(version: 1, default: true) do
      #match 'scores', to: 'scores#index', via: [:options]
      resources :scores
    end
    # scope module: :v2, contraints: ApiContraints.new(version: 2, default: true) do
    #   resources :scores
    # end
  end

  # Authorization
  resources :sessions, :only => [:create]
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'signup' => 'users#new', :as => :signup

  resources :users
  get '/users/:id/generate_api_key' => 'users#generate_api_key', :as => :user_generate_api_key

  resources :games do
    resources :scores
  end

  root 'sessions#new'
end

app/models/score.rb
require 'sanitize'

class Score < ActiveRecord::Base
  belongs_to :game
  before_save :strip_html_from_name

  def as_json(options={})
    result = super.merge(options)
    result['_id'] = self.id.to_s

    result
  end

  private

  def strip_html_from_name
    self.name = Sanitize.clean(self.name)
  end

end

app/controllers/api/v1/scores_controller.rb
module Api
  module V1
    class ScoresController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :restrict_access
      before_action :cors_preflight_check
      after_action :cors_set_access_control_headers
      respond_to :json

      # For all responses in this controller, return the CORS access control headers.
      def cors_set_access_control_headers
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
        headers['Access-Control-Allow-Headers'] = %w{Origin Accept Content-Type X-Requested-With auth_token X-CSRF-Token}.join(',')
        headers['Access-Control-Max-Age'] = "1728000"
      end

      def cors_preflight_check
        if request.method == "OPTIONS"
          headers['Access-Control-Allow-Origin'] = '*'
          headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
          headers['Access-Control-Allow-Headers'] = %w{Origin Accept Content-Type X-Requested-With auth_token X-CSRF-Token}.join(',')
          headers['Access-Control-Max-Age'] = '1728000'
          render :text => '', :content_type => 'text/plain'
        end
      end

      def index
        # TOOD: Change this to use a paging system, but show only the top 10 for now.
        respond_with Score.where(:game_id => params[:game_id]).order('score desc', 'created_at desc').limit(10)
      end

      def show
        respond_with Score.find(params[:id])
      end

      def create
        score = Score.new(score_params)
        #score.game_id = params[:score][:game_id]

        if score.save
          render json: score, status: :created, location: "/api/scores/#{ score.id }"
        else
          render json: score.errors, status: :unprocessable_entity
        end
      end

      private

      # Never trust parameters from the scary internet, only allow the white list through.
      def score_params
        if params.has_key?(:score)
          params.require(:score).permit(:name, :score, :game_id)
        end
      end

      def restrict_access
        valid_api_key = false
        game = params.has_key?(:score) ? Game.find(params[:score][:game_id]) : Game.find(params[:game_id])
        api_key = ApiKey.find_by_access_token(params[:api_key])

        unless api_key.blank? && game.blank?
          valid_api_key = api_key.user_id == game.user.id
        end

        head :unauthorized unless api_key && valid_api_key
      end

    end
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :require_login
  before_action :set_score, only: [:show, :edit, :update, :destroy]
  before_action :set_game

  # GET /scores
  # GET /scores.json
  def index
    @scores = @game.scores.order('score desc', 'created_at desc')
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    @score.game_id = @game.id

    respond_to do |format|
      if @score.save
        format.html { redirect_to [@game, @score], notice: 'Score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to [@game, @score], notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to game_scores_url(@game) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    def set_game
      @game = Game.find(params[:game_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:name, :score, :game_id)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for [@game, @score] do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', [@game, @score] %> |
<%= link_to 'Back', game_scores_path(@game) %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Score</th>
      <th>Game</th>
      <th>Created</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.name %></td>
        <td><%= score.score %></td>
        <td><%= score.game.name %></td>
        <td><%= time_ago_in_words(score.created_at) %> ago</td>
        <td><%= link_to 'Show', [@game, score] %></td>
        <td><%= link_to 'Edit', edit_game_score_path(@game, score) %></td>
        <td><%= link_to 'Destroy', [@game, score], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_game_score_path(@game) %>

<!--
<br><br>

<form id="new-score-form">
  <div class="field">
    <%#= label_tag :name %><br>
    <%#= text_field_tag :name %>
    <input type="text" id="new-name">
  </div>
  <div class="field">
    <%#= label_tag :score %><br>
    <%#= number_field_tag :score %>
    <input type="text" id="new-score">
  </div>
  <div class="field">
    <%#= label_tag :game_id %><br>
    <%#= number_field_tag :game_id, @game.id %>
  </div>
  <%#= submit_tag 'Submit' %>
</form>
-->
<!--
<script>
  $(function() {
    // var data = {
    //   game_id: 1,
    //   api_key: "52444cd19d88c9ebc201bb0464f853ba"
    // };

    // $.ajax({
    //   type: 'GET',
    //   url: 'http://hiscore.herokuapp.com/api/scores',
    //   contentType: 'application/json',
    //   dataType: 'json',
    //   data: data,
    //   success: function(response, status) {
    //     console.log('success: ', response);
    //   },
    //   error: function(response, status, error) {
    //     console.log('error: ', response, status);
    //   }
    // });

    // $('#new-score-form').submit(function(e) {
    //   e.preventDefault();

    //   var data = {
    //     score: {
    //       name: $('#new-name').val(),
    //       score: $('#new-score').val(),
    //       api_key: "<%#= @game.user.api_keys.first.access_token %>",
    //       game_id: <%#= @game.id %>
    //     }
    //   };

    //   console.log(JSON.stringify(data));

    //   $.ajax({
    //     type: 'POST',
    //     url: 'http://hiscore.heroku.com/api/scores',
    //     //url: 'http://localhost:3000/api/scores',
    //     contentType: 'application/json',
    //     dataType: 'json',
    //     data: JSON.stringify(data),
    //     success: function(response, status) {
    //       console.log('success: ', response);
    //     },
    //     error: function(response, status, error) {
    //       console.log('error: ', response, status);
    //     }
    //   });
    //});

    // List all scores (sorted highest to lowest)
    // $.ajax({
    //   type: 'GET',
    //   url: 'http://hiscore.herokuapp.com/api/scores',
    //   contentType: 'application/json',
    //   dataType: 'json',
    //   data: {
    //     game_id: 1,
    //     api_key: "52444cd19d88c9ebc201bb0464f853ba"
    //   },
    //   success: function(response, status) {
    //     console.log('success: ', response);
    //     console.log('status: ', status);
    //   },
    //   error: function(response, status, error) {
    //     console.log('error: ', response);
    //     console.log(status);
    //     console.log(error);
    //     //console.log(response.getResponseHeader());
    //   }
    // });


////////////////////

    // $.get('http://hiscore.herokuapp.com/api/scores', { game_id: 1, api_key: '52444cd19d88c9ebc201bb0464f853ba' }, 'json')
    //   .done(function(data, status, jqXHR) {
    //     console.log(data);
    //     console.log("success")
    //   })
    //   .fail(function(jqXHR, status, error) {
    //     console.log("error");
    //   })
    //   .always(function() {
    //     console.log("finished");
    //   });

    var data = {
      api_key: '52444cd19d88c9ebc201bb0464f853ba',
      score: {
        name: 'Rob',
        score: 10,
        game_id: 1
      }
    };

    $.post('http://hiscore.herokuapp.com/api/scores', data, 'json')
      .done(function(data, status, jqXHR) {
        console.log( "success" );
      })
      .fail(function(jqXHR, status, error) {
        console.log( "error" );
      })
      .always(function() {
        console.log( "finished" );
      });

      //'{"api_key": "152444cd19d88c9ebc201bb0464f853ba", "score": {"name": "Rob", "score": 10, "game_id": 1 }}'

    // $.get('http://localhost:3000/api/scores', { game_id: 1, api_key: '55d43ffd89a1979d5a140ea8d8edf785' }, 'json')
    //   .done(function(data, status, jqXHR) {
    //     console.log(data);
    //     console.log("success")
    //   })
    //   .fail(function(jqXHR, status, error) {
    //     console.log("error");
    //   })
    //   .always(function() {
    //     console.log("finished");
    //   });

    // var data = {
    //   api_key: '55d43ffd89a1979d5a140ea8d8edf785',
    //   score: {
    //     name: 'Rob',
    //     score: 10,
    //     game_id: 1
    //   }
    // };

    // $.post('http://localhost:3000/api/scores', data, 'json')
    //   .done(function(data, status, jqXHR) {
    //     console.log( "success" );
    //   })
    //   .fail(function(jqXHR, status, error) {
    //     console.log( "error" );
    //   })
    //   .always(function() {
    //     console.log( "finished" );
    //   });

////////////////////

    // $.ajax({
    //   type: 'GET',
    //   url: 'http://hiscore.herokuapp.com/api/scores?game_id=1&api_key=52444cd19d88c9ebc201bb0464f853ba',
    //   dataType: 'json',
    //   success: function(response, status) {
    //     console.log('success: ', response);
    //     console.log('status: ', status);
    //   },
    //   error: function(response, status, error) {
    //     console.log('error: ', response);
    //     console.log(status);
    //     console.log(error);
    //     //console.log(response.getResponseHeader());
    //   }
    // });

    // Add new score
    // $('#new-score-form').submit(function(e) {
    //   e.preventDefault();

    //   var data = {
    //     score: {
    //       name: $('#new-name').val(),
    //       score: $('#new-score').val(),
    //       api_key: '152444cd19d88c9ebc201bb0464f853ba',
    //       game_id: 1
    //     }
    //   };



      // $.ajax({
      //   type: 'POST',
      //   url: 'http://hiscore.herokuapp.com/api/scores',
      //   contentType: 'application/json',
      //   dataType: 'json',
      //   data: data,
      //   success: function(response, status) {
      //     console.log('success: ', response);
      //   },
      //   error: function(response, status, error) {
      //     console.log('error: ', response, status);
      //   }
      // });

      // curl -X POST -D headers.txt -H 'Content-Type: application/json' -d '{"api_key": "55d43ffd89a1979d5a140ea8d8edf785", "score": {"name": "Rob", "score": 10, "game_id": 1 }}' http://localhost:3000/api/scores

      // curl -X POST -D headers.txt -H 'Content-Type: application/json' -d '{"api_key": "52444cd19d88c9ebc201bb0464f853ba", "score": {"name": "Rob", "score": 10, "game_id": 1 }}' http://hiscore.herokuapp.com/api/scores
  });
</script>
-->

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', game_scores_path(@game) %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @score.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<p>
  <strong>Game:</strong>
  <%= @score.game_id %>
</p>

<%= link_to 'Edit', edit_game_score_path(@game, @score) %> |
<%= link_to 'Back', game_scores_path(@game) %>