config/routes.rb
require 'api_contraints'

Highscore::Application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, contraints: ApiContraints.new(version: 1, default: true) do
      #match 'scores', to: 'scores#index', via: [:options]
      resources :scores
    end
    # scope module: :v2, contraints: ApiContraints.new(version: 2, default: true) do
    #   resources :scores
    # end
  end

  # Authorization
  resources :sessions, :only => [:create]
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'signup' => 'users#new', :as => :signup

  resources :users
  get '/users/:id/generate_api_key' => 'users#generate_api_key', :as => :user_generate_api_key

  resources :games do
    resources :scores
  end

  root 'sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  has_many :api_keys
  has_secure_password

  validates :email,
    :presence => true,
    :uniqueness => true,
    :length => { :maximum => 255 }#,
    # :format => { :with => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i }

  validates :name,
    :length => { :maximum => 255 },
    :allow_blank => true

  validates :password,
    :presence => { :on => :create }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login # disable signup, :except => [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :generate_api_key]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @games = @user.games
    @api_key = @user.api_keys.first.blank? ? 'not set' : @user.api_keys.first.access_token
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    puts @user.password
    @user.password_confirmation = @user.password # disable password confirmation

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def generate_api_key
    @user.api_keys.each do |api_key|
      api_key.destroy
    end
    @user.api_keys << ApiKey.new
    redirect_to @user
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :website)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Website</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.website %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%- if alert %>
  <p class="warning" style="color: #eeb111">
    <%= alert %>
  </p>
<%- end %>

<%= form_for @user, :class => 'user-form' do |f| %>
  <%- if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, 'error') %>
        prohibited this user from being saved:
      </h2>
      <ul>
        <%- @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%- end %>
      </ul>
    </div>
  <%- end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :id => "signup-email", :autofocus => "autofocus" %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, :id => "signup-password" %>
  </div>
  <div class="actions">
    <%= f.submit "Signup", :class => "button plain" %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @user.website %>
</p>

<p>
  <strong>Games:</strong>
  <ul>
    <%- @games.each do |game| %>
      <li><%= link_to game.name, game %></li>
    <%- end %>
  </ul>
</p>

<p>
  <strong>API Key:</strong>
  <%= @api_key %><br>
  <%= link_to 'regenerate', user_generate_api_key_path(@user) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>